In [126]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import pdist, squareform
import math

In [127]:
movies_df=pd.read_csv('./movie_lens/movies.csv')

In [128]:
ratings_df=pd.read_csv('./movie_lens/ratings.csv')

In [129]:
ratings_df

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [130]:
movies_df['year'] = movies_df.title.str.extract('(\(\d\d\d\d\))',expand=False)

In [131]:
movies_df['year'] = movies_df.year.str.extract('(\d\d\d\d)',expand=False)

In [132]:
movies_df['title'] = movies_df.title.str.replace(' (\(\d\d\d\d\))', '')

C:\Users\sofia\AppData\Local\Temp/ipykernel_2252/2097454755.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  movies_df['title'] = movies_df.title.str.replace(' (\(\d\d\d\d\))', '')

In [133]:
movies_df.drop(columns=['genres'],inplace=True)

In [134]:
movies_df

      movieId                               title  year
0           1                           Toy Story  1995
1           2                             Jumanji  1995
2           3                    Grumpier Old Men  1995
3           4                   Waiting to Exhale  1995
4           5         Father of the Bride Part II  1995
...       ...                                 ...   ...
9737   193581  Black Butler: Book of the Atlantic  2017
9738   193583               No Game No Life: Zero  2017
9739   193585                               Flint  2017
9740   193587        Bungo Stray Dogs: Dead Apple  2018
9741   193609        Andrew Dice Clay: Dice Rules  1991

[9742 rows x 3 columns]

In [135]:
movies_df=movies_df.loc[(movies_df.loc[:,'year']>'1995')]
movies_df

      movieId                                              title  year
54         61                                     Eye for an Eye  1996
56         63  Don't Be a Menace to South Central While Drink...  1996
57         64                                      Two if by Sea  1996
58         65                                           Bio-Dome  1996
59         66                 Lawnmower Man 2: Beyond Cyberspace  1996
...       ...                                                ...   ...
9736   193579                  Jon Stewart Has Left the Building  2015
9737   193581                 Black Butler: Book of the Atlantic  2017
9738   193583                              No Game No Life: Zero  2017
9739   193585                                              Flint  2017
9740   193587                       Bungo Stray Dogs: Dead Apple  2018

[5837 rows x 3 columns]

In [136]:
userInput = [
{'title':'Titanic', 'rating':5},
{'title':'Mulan', 'rating':5},
{'title':'Crazy, Stupid, Love.', 'rating':4.5},
{'title':'Pirates of the Caribbean: The Curse of the Black Pearl', 'rating':4.5},
{'title':'Disturbia', 'rating':4.5}
]
choice_Movies = pd.DataFrame(userInput)

In [137]:
filtro_movies_df=movies_df[np.isin(movies_df, choice_Movies)]

In [138]:
choice_movies_1 = pd.merge(filtro_movies_df, choice_Movies)

In [139]:
choice_movies_1

   movieId                                              title  year  rating
0     1721                                            Titanic  1997     5.0
1     1907                                              Mulan  1998     5.0
2     6539  Pirates of the Caribbean: The Curse of the Bla...  2003     4.5
3    52458                                          Disturbia  2007     4.5
4    88163                               Crazy, Stupid, Love.  2011     4.5

In [140]:
choice_movies_1.drop(columns=['year'],inplace=True)

In [141]:
choice_movies_1

   movieId                                              title  rating
0     1721                                            Titanic     5.0
1     1907                                              Mulan     5.0
2     6539  Pirates of the Caribbean: The Curse of the Bla...     4.5
3    52458                                          Disturbia     4.5
4    88163                               Crazy, Stupid, Love.     4.5

In [142]:
filtro_rating_df=ratings_df[np.isin(ratings_df['movieId'], choice_movies_1['movieId'].tolist())]
filtro_rating_df

        userId  movieId  rating   timestamp
415          4     1907     3.0   964540505
967          7     6539     4.5  1106636584
1129        10     1907     4.0  1455306183
1226        10    88163     4.0  1455357504
1313        11     1721     5.0   902154989
...        ...      ...     ...         ...
99381      608     6539     4.0  1117162561
99654      610     1721     3.0  1479544112
99968      610     6539     4.0  1493844694
100241     610    52458     3.0  1493849671
100517     610    88163     4.0  1493845317

[375 rows x 4 columns]

In [143]:
filtro_rating_df_1 =filtro_rating_df.groupby(['userId'])

In [144]:
filtro_rating_df_2 = sorted(filtro_rating_df_1, key=lambda x: len(x[1]), reverse=True)

In [145]:
filtro_rating_df_2

[(177,
         userId  movieId  rating   timestamp
  25109     177     1721     5.0  1435890496
  25115     177     1907     3.0  1435535032
  25379     177     6539     5.0  1435523568
  25572     177    52458     2.5  1435529758
  25734     177    88163     4.0  1435526726),
 (414,
         userId  movieId  rating   timestamp
  62897     414     1721     4.0   961514186
  62935     414     1907     4.0  1039532289
  64152     414     6539     4.5  1058630859
  64614     414    52458     3.0  1190571083
  64837     414    88163     4.0  1324237568),
 (68,
         userId  movieId  rating   timestamp
  10648      68     1721     3.0  1158531226
  11109      68     6539     5.0  1158531197
  11336      68    52458     4.5  1269123045
  11549      68    88163     4.0  1359323517),
 (232,
         userId  movieId  rating   timestamp
  33978     232     1721     4.5  1182909244
  33980     232     1907     3.5  1076956051
  34214     232     6539     4.5  1078451197
  34587     232    52458     3.5  1180747388),
 (249,
         userId  movieId  rating   timestamp
  36504     249     1721     2.0  1347318423
  36734     249     6539     4.0  1346757892
  36904     249    52458     4.0  1415415805
  37133     249    88163     4.5  1347317835),
 (483,
         userId  movieId  rating   timestamp
  77416     483     1721     2.0  1181496542
  77425     483     1907     3.5  1181495841
  77667     483     6539     4.0  1178213524
  77872     483    88163     4.0  1330911991),
 (610,
          userId  movieId  rating   timestamp
  99654      610     1721     3.0  1479544112
  99968      610     6539     4.0  1493844694
  100241     610    52458     3.0  1493849671
  100517     610    88163     4.0  1493845317),
 (41,
        userId  movieId  rating   timestamp
  5698      41     1721     5.0  1458939738
  5759      41     6539     3.0  1458939642
  5838      41    88163     4.0  1458942860),
 (62,
        userId  movieId  rating   timestamp
  8825      62     1721     4.0  1521822338
  8885      62     6539     4.0  1521488598
  9027      62    88163     4.0  1521489757),
 (111,
         userId  movieId  rating   timestamp
  17312     111     1721     4.0  1518902680
  17318     111     1907     3.5  1518640826
  17461     111     6539     3.0  1516140846),
 (129,
         userId  movieId  rating   timestamp
  19718     129     1721     3.5  1167375999
  19719     129     1907     4.5  1167378161
  19784     129     6539     4.0  1167375893),
 (274,
         userId  movieId  rating   timestamp
  39523     274     1721     3.5  1171492429
  40060     274     6539     4.0  1171491579
  40381     274    52458     2.5  1179008909),
 (292,
         userId  movieId  rating   timestamp
  43581     292     1721     4.0  1265680427
  43583     292     1907     3.5  1293562953
  43744     292     6539     4.0  1219624973),
 (298,
         userId  movieId  rating   timestamp
  44919     298     6539     2.5  1447560174
  45096     298    52458     2.5  1447599380
  45307     298    88163     3.0  1447517011),
 (307,
         userId  movieId  rating   timestamp
  46995     307     1721     2.0  1186161016
  47408     307     6539     3.0  1186161691
  47635     307    52458     2.5  1186878639),
 (339,
         userId  movieId  rating   timestamp
  52073     339     1721     4.0  1460346592
  52154     339     6539     3.0  1460185149
  52301     339    88163     4.0  1460518823),
 (351,
         userId  movieId  rating   timestamp
  53072     351     1721     4.0  1326106611
  53114     351     6539     4.0  1326106624
  53178     351    88163     4.5  1326061752),
 (380,
         userId  movieId  rating   timestamp
  57103     380     1721     2.0  1493667395
  57119     380     1907     5.0  1493423190
  57505     380     6539     5.0  1493419904),
 (381,
         userId  movieId  rating   timestamp
  58200     381     1721     3.5  1164877331
  58206     381     1907     4.0  1167543323
  58379     381     6539     3.5  1200823941),
 (425,
         userId  movieId  rating   timestamp
  66023     425     1721     3.5  1085477546
  66029     425     1907     3.0  1106482769
  66139     425     6539     3.5  1085492366),
 (428,
         userId  movieId  rating   timestamp
  66466     428     1721     1.0  1111623138
  66470     428     1907     2.0  1111523978
  66637     428     6539     2.5  1111489266),
 (438,
         userId  movieId  rating   timestamp
  67726     438     1721     3.0  1105666341
  67737     438     1907     2.5  1109902304
  68045     438     6539     5.0  1105649805),
 (474,
         userId  movieId  rating   timestamp
  73581     474     1721     4.0   974668977
  73601     474     1907     3.5  1087832623
  74623     474     6539     3.5  1075129578),
 (490,
         userId  movieId  rating   timestamp
  79139     490     1721     3.0  1328229354
  79165     490     6539     3.0  1328145462
  79224     490    88163     3.0  1328145406),
 (509,
         userId  movieId  rating   timestamp
  80439     509     1907     4.0  1436000045
  80547     509     6539     3.5  1435993253
  80762     509    88163     4.0  1435994889),
 (525,
         userId  movieId  rating   timestamp
  82708     525     1907     3.5  1476480287
  82864     525     6539     4.5  1476479347
  83029     525    88163     4.0  1476477734),
 (534,
         userId  movieId  rating   timestamp
  83643     534     1721     4.5  1459787998
  83649     534     1907     4.0  1459787997
  83750     534     6539     4.5  1459787998),
 (560,
         userId  movieId  rating   timestamp
  86191     560     1721     3.5  1469648742
  86194     560     1907     3.5  1469654145
  86326     560     6539     3.5  1469647825),
 (573,
         userId  movieId  rating   timestamp
  88759     573     1721     1.5  1186722299
  88850     573     6539     5.0  1186589649
  88908     573    52458     3.5  1248842600),
 (599,
         userId  movieId  rating   timestamp
  93206     599     1721     3.0  1498524231
  94145     599     6539     2.5  1498516218
  94825     599    88163     3.5  1498537670),
 (608,
         userId  movieId  rating   timestamp
  98948     608     1721     2.0  1117408294
  98970     608     1907     3.5  1117504918
  99381     608     6539     4.0  1117162561),
 (10,
        userId  movieId  rating   timestamp
  1129      10     1907     4.0  1455306183
  1226      10    88163     4.0  1455357504),
 (18,
        userId  movieId  rating   timestamp
  1899      18     1721     4.0  1455748443
  2009      18     6539     4.5  1455049808),
 (21,
        userId  movieId  rating   timestamp
  3275      21     1721     3.5  1418846922
  3384      21     6539     4.0  1419795351),
 (27,
        userId  movieId  rating  timestamp
  4128      27     1721     5.0  965149814
  4130      27     1907     4.0  962685318),
 (34,
        userId  movieId  rating   timestamp
  5204      34     1721     0.5  1162048752
  5251      34     6539     5.0  1162047962),
 (45,
        userId  movieId  rating   timestamp
  6646      45     1721     4.0  1091306055
  6855      45     6539     5.0  1121724104),
 (50,
        userId  movieId  rating   timestamp
  7172      50     1721     3.0  1514237992
  7221      50     6539     3.0  1514238028),
 (57,
        userId  movieId  rating  timestamp
  8303      57     1721     2.0  965799094
  8315      57     1907     4.0  972173465),
 (64,
        userId  movieId  rating   timestamp
  9614      64     1907     4.0  1161566450
  9861      64     6539     4.0  1161520011),
 (82,
         userId  movieId  rating   timestamp
  12809      82     1721     2.5  1084464232
  12926      82     6539     4.5  1084467083),
 (86,
         userId  movieId  rating   timestamp
  13421      86     1721     3.5  1344082821
  13453      86     6539     4.0  1344082601),
 (115,
         userId  movieId  rating  timestamp
  18203     115     1721     4.0  957647634
  18205     115     1907     5.0  948322710),
 (116,
         userId  movieId  rating   timestamp
  18317     116     1721     4.0  1337199824
  18344     116     6539     4.0  1337200005),
 (119,
         userId  movieId  rating   timestamp
  18597     119     6539     4.0  1436563804
  18670     119    88163     4.0  1448750538),
 (125,
         userId  movieId  rating   timestamp
  19306     125     6539     4.0  1474481294
  19429     125    88163     4.0  1474570184),
 (132,
         userId  movieId  rating   timestamp
  20039     132     1721     3.0  1157921273
  20189     132     6539     3.0  1157920895),
 (140,
         userId  movieId  rating   timestamp
  21270     140     1721     4.0   942841219
  21592     140     6539     3.5  1079472360),
 (143,
         userId  movieId  rating   timestamp
  21902     143     1721     4.0  1444880204
  21919     143     6539     3.0  1444769135),
 (153,
         userId  movieId  rating   timestamp
  22459     153     1721     2.0  1525550658
  22461     153     1907     3.0  1525552223),
 (156,
         userId  movieId  rating   timestamp
  22869     156     1721     3.0   939854571
  23061     156     6539     4.0  1106881798),
 (169,
         userId  movieId  rating   timestamp
  24409     169     1721     5.0  1078284611
  24557     169     6539     4.5  1059427432),
 (185,
         userId  movieId  rating   timestamp
  27274     185     1721     3.0  1044311157
  27276     185     1907     3.0  1044311830),
 (200,
         userId  movieId  rating   timestamp
  29019     200     1721     2.5  1229886327
  29155     200     6539     4.0  1229886346),
 (213,
         userId  movieId  rating   timestamp
  30533     213     1721     4.0  1316195659
  30564     213     6539     4.0  1316197095),
 (219,
         userId  movieId  rating   timestamp
  31661     219     1721     0.5  1214043346
  31876     219     6539     4.5  1194686217),
 (220,
         userId  movieId  rating   timestamp
  32117     220     1721     5.0  1230055822
  32191     220     6539     5.0  1230055569),
 (221,
         userId  movieId  rating   timestamp
  32394     221     1721     3.0  1111177393
  32517     221     6539     3.5  1111176254),
 (222,
         userId  movieId  rating   timestamp
  32656     222     1721     2.5  1391375337
  32726     222     6539     3.5  1391350186),
 (226,
         userId  movieId  rating   timestamp
  33206     226     1721     1.5  1114838120
  33439     226     6539     4.5  1095663760),
 (230,
         userId  movieId  rating   timestamp
  33793     230     1721     3.0  1196304348
  33842     230     6539     5.0  1196304426),
 (233,
         userId  movieId  rating   timestamp
  34790     233     1721     3.5  1529334058
  34831     233     6539     3.0  1529333698),
 (254,
         userId  movieId  rating   timestamp
  37593     254     1721     3.5  1180446472
  37633     254     6539     4.0  1180446204),
 (263,
         userId  movieId  rating   timestamp
  38313     263     1721     4.0   940384199
  38412     263     6539     4.0  1090948146),
 (280,
         userId  movieId  rating   timestamp
  41286     280     1721     4.0  1348435240
  41350     280     6539     3.5  1348435219),
 (282,
         userId  movieId  rating   timestamp
  41524     282     1721     3.0  1378490504
  41641     282     6539     4.0  1378498775),
 (286,
         userId  movieId  rating   timestamp
  41900     286     1721     1.0  1119561957
  41955     286     6539     4.0  1119562462),
 (288,
         userId  movieId  rating   timestamp
  42410     288     1721     3.0   976121266
  42998     288     6539     4.0  1083091556),
 (301,
         userId  movieId  rating   timestamp
  45577     301     1721     1.5  1211377856
  45616     301     6539     4.0  1211377789),
 (304,
         userId  movieId  rating  timestamp
  45899     304     1721     5.0  885216165
  45907     304     1907     4.0  920201350),
 (305,
         userId  movieId  rating   timestamp
  46069     305     1721     3.5  1460365965
  46458     305    88163     4.0  1460303544),
 (318,
         userId  movieId  rating   timestamp
  49123     318     1907     3.5  1275845120
  49298     318     6539     3.5  1237233388),
 (328,
         userId  movieId  rating   timestamp
  50762     328     1907     3.0  1494210756
  50839     328     6539     3.5  1494212242),
 (352,
         userId  movieId  rating   timestamp
  53240     352     1721     4.0  1493673487
  53319     352     6539     4.0  1493675365),
 (357,
         userId  movieId  rating   timestamp
  54277     357     1721     4.0  1348611252
  54501     357    88163     4.5  1348611538),
 (358,
         userId  movieId  rating   timestamp
  54508     358     1721     5.0  1339546519
  54545     358    88163     4.0  1339546383),
 (361,
         userId  movieId  rating   timestamp
  54678     361     1721     2.0  1204045530
  54717     361     6539     3.5  1204045778),
 (365,
         userId  movieId  rating   timestamp
  54979     365     6539     3.5  1488332413
  55069     365    88163     2.5  1488594759),
 (370,
         userId  movieId  rating   timestamp
  56029     370     1721     3.5  1159162916
  56069     370     6539     4.0  1159163431),
 (382,
         userId  movieId  rating   timestamp
  58618     382     1721     5.0  1515160906
  58620     382     1907     4.5  1515161436),
 (387,
         userId  movieId  rating   timestamp
  59525     387     1907     2.5  1171934560
  59982     387     6539     3.5  1094876883),
 (401,
         userId  movieId  rating   timestamp
  61211     401     1907     3.5  1510455626
  61226     401     6539     3.5  1510455689),
 (416,
         userId  movieId  rating   timestamp
  65106     416     1721     0.5  1187496464
  65130     416     6539     2.0  1187496479),
 (420,
         userId  movieId  rating   timestamp
  65484     420     1721     4.0  1218207717
  65538     420     6539     4.0  1218207173),
 (432,
         userId  movieId  rating   timestamp
  66861     432     1721     4.0  1316391552
  66950     432     6539     0.5  1316391748),
 (448,
         userId  movieId  rating   timestamp
  69531     448     6539     3.5  1066291868
  69965     448    88163     3.5  1358608911),
 (462,
         userId  movieId  rating   timestamp
  71670     462     1721     2.5  1269929058
  71825     462     6539     4.0  1137445122),
 (477,
         userId  movieId  rating   timestamp
  75591     477     1721     3.5  1200939764
  75843     477     6539     3.0  1200945523),
 (480,
         userId  movieId  rating   timestamp
  76445     480     1721     4.0  1179178328
  76800     480     6539     3.0  1179163366),
 (484,
         userId  movieId  rating   timestamp
  78025     484     1721     3.0  1342295829
  78221     484    88163     4.0  1342297660),
 (489,
         userId  movieId  rating   timestamp
  78682     489     1721     3.5  1333101365
  78943     489     6539     2.0  1333101545),
 (495,
         userId  movieId  rating   timestamp
  79547     495     1721     5.0  1458635859
  79617     495     6539     2.5  1458635449),
 (517,
         userId  movieId  rating   timestamp
  81656     517     1721     3.5  1487953281
  81783     517     6539     2.5  1488397735),
 (523,
         userId  movieId  rating   timestamp
  82420     523     1721     5.0  1503126287
  82436     523     6539     4.5  1507987910),
 (537,
         userId  movieId  rating   timestamp
  84166     537     1721     3.0  1424141915
  84175     537     6539     5.0  1424317101),
 (542,
         userId  movieId  rating   timestamp
  84439     542     1721     3.0  1163387005
  84493     542     6539     4.0  1163386585),
 (561,
         userId  movieId  rating   timestamp
  86703     561     1721     3.0  1491091198
  86884     561     6539     4.5  1491095038),
 (562,
         userId  movieId  rating   timestamp
  87247     562     6539     3.0  1368893993
  87311     562    88163     5.0  1368896635),
 (563,
         userId  movieId  rating   timestamp
  87346     563     1907     3.5  1448749252
  87477     563    88163     3.5  1439933450),
 (570,
         userId  movieId  rating   timestamp
  88336     570     1721     3.0  1181477324
  88391     570     6539     3.5  1181479344),
 (580,
         userId  movieId  rating   timestamp
  89450     580     1721     4.0  1167790146
  89629     580     6539     4.0  1167673988),
 (583,
         userId  movieId  rating   timestamp
  89862     583     1721     4.0  1481474572
  89865     583     1907     4.0  1481474543),
 (590,
         userId  movieId  rating   timestamp
  90760     590     1721     3.5  1258416578
  91086     590     6539     4.0  1258420924),
 (593,
         userId  movieId  rating   timestamp
  91440     593     1721     4.0  1181007536
  91477     593     6539     1.0  1181007588),
 (596,
         userId  movieId  rating   timestamp
  91827     596     1907     4.0  1535709651
  91939     596     6539     3.0  1535708248),
 (606,
         userId  movieId  rating   timestamp
  97659     606     1721     4.0  1171325893
  98158     606     6539     3.0  1172015230),
 (4,
       userId  movieId  rating  timestamp
  415       4     1907     3.0  964540505),
 (7,
       userId  movieId  rating   timestamp
  967       7     6539     4.5  1106636584),
 (11,
        userId  movieId  rating  timestamp
  1313      11     1721     5.0  902154989),
 (12,
        userId  movieId  rating   timestamp
  1337      12     1721     5.0  1247264463),
 (13,
        userId  movieId  rating  timestamp
  1363      13     1721     4.0  987456818),
 (19,
        userId  movieId  rating  timestamp
  2617      19     1907     3.0  965709025),
 (20,
        userId  movieId  rating   timestamp
  3035      20     1907     5.0  1054038097),
 (22,
        userId  movieId  rating   timestamp
  3715      22     6539     2.5  1268727433),
 (28,
        userId  movieId  rating   timestamp
  4501      28     6539     2.0  1242031882),
 (33,
        userId  movieId  rating  timestamp
  5144      33     1721     4.0  939646820),
 (39,
        userId  movieId  rating  timestamp
  5513      39     1907     2.0  974788976),
 (47,
        userId  movieId  rating   timestamp
  6943      47     1721     3.5  1496209715),
 (63,
        userId  movieId  rating   timestamp
  9328      63     6539     4.0  1443200039),
 (66,
         userId  movieId  rating   timestamp
  10274      66     6539     3.5  1093747292),
 (67,
         userId  movieId  rating   timestamp
  10350      67     6539     4.5  1501273908),
 (69,
         userId  movieId  rating   timestamp
  11640      69     1721     4.0  1021643744),
 (73,
         userId  movieId  rating   timestamp
  11843      73     6539     4.5  1464196275),
 (75,
         userId  movieId  rating   timestamp
  12231      75     1721     2.5  1158967893),
 (76,
         userId  movieId  rating   timestamp
  12334      76     6539     2.0  1439168232),
 (77,
         userId  movieId  rating   timestamp
  12401      77     6539     4.0  1535107525),
 (80,
         userId  movieId  rating   timestamp
  12597      80     6539     4.0  1377308697),
 (83,
         userId  movieId  rating   timestamp
  13031      83     6539     3.5  1333843436),
 (91,
         userId  movieId  rating   timestamp
  14643      91     6539     5.0  1112712353),
 (93,
         userId  movieId  rating  timestamp
  14781      93     1721     5.0  942947205),
 (96,
         userId  movieId  rating  timestamp
  15086      96     1721     2.0  964773788),
 (98,
         userId  movieId  rating   timestamp
  15223      98    88163     5.0  1532457701),
 (103,
         userId  movieId  rating   timestamp
  15793     103     6539     4.5  1431957197),
 (104,
         userId  movieId  rating   timestamp
  16129     104     6539     3.0  1161675780),
 (105,
         userId  movieId  rating   timestamp
  16465     105     6539     4.0  1446573300),
 (106,
         userId  movieId  rating   timestamp
  16945     106     6539     5.0  1467360730),
 (108,
         userId  movieId  rating   timestamp

In [146]:
filtro_rating_df_3 = filtro_rating_df_2[0:100]

In [147]:
filtro_rating_df_3

[(177,
         userId  movieId  rating   timestamp
  25109     177     1721     5.0  1435890496
  25115     177     1907     3.0  1435535032
  25379     177     6539     5.0  1435523568
  25572     177    52458     2.5  1435529758
  25734     177    88163     4.0  1435526726),
 (414,
         userId  movieId  rating   timestamp
  62897     414     1721     4.0   961514186
  62935     414     1907     4.0  1039532289
  64152     414     6539     4.5  1058630859
  64614     414    52458     3.0  1190571083
  64837     414    88163     4.0  1324237568),
 (68,
         userId  movieId  rating   timestamp
  10648      68     1721     3.0  1158531226
  11109      68     6539     5.0  1158531197
  11336      68    52458     4.5  1269123045
  11549      68    88163     4.0  1359323517),
 (232,
         userId  movieId  rating   timestamp
  33978     232     1721     4.5  1182909244
  33980     232     1907     3.5  1076956051
  34214     232     6539     4.5  1078451197
  34587     232    52458     3.5  1180747388),
 (249,
         userId  movieId  rating   timestamp
  36504     249     1721     2.0  1347318423
  36734     249     6539     4.0  1346757892
  36904     249    52458     4.0  1415415805
  37133     249    88163     4.5  1347317835),
 (483,
         userId  movieId  rating   timestamp
  77416     483     1721     2.0  1181496542
  77425     483     1907     3.5  1181495841
  77667     483     6539     4.0  1178213524
  77872     483    88163     4.0  1330911991),
 (610,
          userId  movieId  rating   timestamp
  99654      610     1721     3.0  1479544112
  99968      610     6539     4.0  1493844694
  100241     610    52458     3.0  1493849671
  100517     610    88163     4.0  1493845317),
 (41,
        userId  movieId  rating   timestamp
  5698      41     1721     5.0  1458939738
  5759      41     6539     3.0  1458939642
  5838      41    88163     4.0  1458942860),
 (62,
        userId  movieId  rating   timestamp
  8825      62     1721     4.0  1521822338
  8885      62     6539     4.0  1521488598
  9027      62    88163     4.0  1521489757),
 (111,
         userId  movieId  rating   timestamp
  17312     111     1721     4.0  1518902680
  17318     111     1907     3.5  1518640826
  17461     111     6539     3.0  1516140846),
 (129,
         userId  movieId  rating   timestamp
  19718     129     1721     3.5  1167375999
  19719     129     1907     4.5  1167378161
  19784     129     6539     4.0  1167375893),
 (274,
         userId  movieId  rating   timestamp
  39523     274     1721     3.5  1171492429
  40060     274     6539     4.0  1171491579
  40381     274    52458     2.5  1179008909),
 (292,
         userId  movieId  rating   timestamp
  43581     292     1721     4.0  1265680427
  43583     292     1907     3.5  1293562953
  43744     292     6539     4.0  1219624973),
 (298,
         userId  movieId  rating   timestamp
  44919     298     6539     2.5  1447560174
  45096     298    52458     2.5  1447599380
  45307     298    88163     3.0  1447517011),
 (307,
         userId  movieId  rating   timestamp
  46995     307     1721     2.0  1186161016
  47408     307     6539     3.0  1186161691
  47635     307    52458     2.5  1186878639),
 (339,
         userId  movieId  rating   timestamp
  52073     339     1721     4.0  1460346592
  52154     339     6539     3.0  1460185149
  52301     339    88163     4.0  1460518823),
 (351,
         userId  movieId  rating   timestamp
  53072     351     1721     4.0  1326106611
  53114     351     6539     4.0  1326106624
  53178     351    88163     4.5  1326061752),
 (380,
         userId  movieId  rating   timestamp
  57103     380     1721     2.0  1493667395
  57119     380     1907     5.0  1493423190
  57505     380     6539     5.0  1493419904),
 (381,
         userId  movieId  rating   timestamp
  58200     381     1721     3.5  1164877331
  58206     381     1907     4.0  1167543323
  58379     381     6539     3.5  1200823941),
 (425,
         userId  movieId  rating   timestamp
  66023     425     1721     3.5  1085477546
  66029     425     1907     3.0  1106482769
  66139     425     6539     3.5  1085492366),
 (428,
         userId  movieId  rating   timestamp
  66466     428     1721     1.0  1111623138
  66470     428     1907     2.0  1111523978
  66637     428     6539     2.5  1111489266),
 (438,
         userId  movieId  rating   timestamp
  67726     438     1721     3.0  1105666341
  67737     438     1907     2.5  1109902304
  68045     438     6539     5.0  1105649805),
 (474,
         userId  movieId  rating   timestamp
  73581     474     1721     4.0   974668977
  73601     474     1907     3.5  1087832623
  74623     474     6539     3.5  1075129578),
 (490,
         userId  movieId  rating   timestamp
  79139     490     1721     3.0  1328229354
  79165     490     6539     3.0  1328145462
  79224     490    88163     3.0  1328145406),
 (509,
         userId  movieId  rating   timestamp
  80439     509     1907     4.0  1436000045
  80547     509     6539     3.5  1435993253
  80762     509    88163     4.0  1435994889),
 (525,
         userId  movieId  rating   timestamp
  82708     525     1907     3.5  1476480287
  82864     525     6539     4.5  1476479347
  83029     525    88163     4.0  1476477734),
 (534,
         userId  movieId  rating   timestamp
  83643     534     1721     4.5  1459787998
  83649     534     1907     4.0  1459787997
  83750     534     6539     4.5  1459787998),
 (560,
         userId  movieId  rating   timestamp
  86191     560     1721     3.5  1469648742
  86194     560     1907     3.5  1469654145
  86326     560     6539     3.5  1469647825),
 (573,
         userId  movieId  rating   timestamp
  88759     573     1721     1.5  1186722299
  88850     573     6539     5.0  1186589649
  88908     573    52458     3.5  1248842600),
 (599,
         userId  movieId  rating   timestamp
  93206     599     1721     3.0  1498524231
  94145     599     6539     2.5  1498516218
  94825     599    88163     3.5  1498537670),
 (608,
         userId  movieId  rating   timestamp
  98948     608     1721     2.0  1117408294
  98970     608     1907     3.5  1117504918
  99381     608     6539     4.0  1117162561),
 (10,
        userId  movieId  rating   timestamp
  1129      10     1907     4.0  1455306183
  1226      10    88163     4.0  1455357504),
 (18,
        userId  movieId  rating   timestamp
  1899      18     1721     4.0  1455748443
  2009      18     6539     4.5  1455049808),
 (21,
        userId  movieId  rating   timestamp
  3275      21     1721     3.5  1418846922
  3384      21     6539     4.0  1419795351),
 (27,
        userId  movieId  rating  timestamp
  4128      27     1721     5.0  965149814
  4130      27     1907     4.0  962685318),
 (34,
        userId  movieId  rating   timestamp
  5204      34     1721     0.5  1162048752
  5251      34     6539     5.0  1162047962),
 (45,
        userId  movieId  rating   timestamp
  6646      45     1721     4.0  1091306055
  6855      45     6539     5.0  1121724104),
 (50,
        userId  movieId  rating   timestamp
  7172      50     1721     3.0  1514237992
  7221      50     6539     3.0  1514238028),
 (57,
        userId  movieId  rating  timestamp
  8303      57     1721     2.0  965799094
  8315      57     1907     4.0  972173465),
 (64,
        userId  movieId  rating   timestamp
  9614      64     1907     4.0  1161566450
  9861      64     6539     4.0  1161520011),
 (82,
         userId  movieId  rating   timestamp
  12809      82     1721     2.5  1084464232
  12926      82     6539     4.5  1084467083),
 (86,
         userId  movieId  rating   timestamp
  13421      86     1721     3.5  1344082821
  13453      86     6539     4.0  1344082601),
 (115,
         userId  movieId  rating  timestamp
  18203     115     1721     4.0  957647634
  18205     115     1907     5.0  948322710),
 (116,
         userId  movieId  rating   timestamp
  18317     116     1721     4.0  1337199824
  18344     116     6539     4.0  1337200005),
 (119,
         userId  movieId  rating   timestamp
  18597     119     6539     4.0  1436563804
  18670     119    88163     4.0  1448750538),
 (125,
         userId  movieId  rating   timestamp
  19306     125     6539     4.0  1474481294
  19429     125    88163     4.0  1474570184),
 (132,
         userId  movieId  rating   timestamp
  20039     132     1721     3.0  1157921273
  20189     132     6539     3.0  1157920895),
 (140,
         userId  movieId  rating   timestamp
  21270     140     1721     4.0   942841219
  21592     140     6539     3.5  1079472360),
 (143,
         userId  movieId  rating   timestamp
  21902     143     1721     4.0  1444880204
  21919     143     6539     3.0  1444769135),
 (153,
         userId  movieId  rating   timestamp
  22459     153     1721     2.0  1525550658
  22461     153     1907     3.0  1525552223),
 (156,
         userId  movieId  rating   timestamp
  22869     156     1721     3.0   939854571
  23061     156     6539     4.0  1106881798),
 (169,
         userId  movieId  rating   timestamp
  24409     169     1721     5.0  1078284611
  24557     169     6539     4.5  1059427432),
 (185,
         userId  movieId  rating   timestamp
  27274     185     1721     3.0  1044311157
  27276     185     1907     3.0  1044311830),
 (200,
         userId  movieId  rating   timestamp
  29019     200     1721     2.5  1229886327
  29155     200     6539     4.0  1229886346),
 (213,
         userId  movieId  rating   timestamp
  30533     213     1721     4.0  1316195659
  30564     213     6539     4.0  1316197095),
 (219,
         userId  movieId  rating   timestamp
  31661     219     1721     0.5  1214043346
  31876     219     6539     4.5  1194686217),
 (220,
         userId  movieId  rating   timestamp
  32117     220     1721     5.0  1230055822
  32191     220     6539     5.0  1230055569),
 (221,
         userId  movieId  rating   timestamp
  32394     221     1721     3.0  1111177393
  32517     221     6539     3.5  1111176254),
 (222,
         userId  movieId  rating   timestamp
  32656     222     1721     2.5  1391375337
  32726     222     6539     3.5  1391350186),
 (226,
         userId  movieId  rating   timestamp
  33206     226     1721     1.5  1114838120
  33439     226     6539     4.5  1095663760),
 (230,
         userId  movieId  rating   timestamp
  33793     230     1721     3.0  1196304348
  33842     230     6539     5.0  1196304426),
 (233,
         userId  movieId  rating   timestamp
  34790     233     1721     3.5  1529334058
  34831     233     6539     3.0  1529333698),
 (254,
         userId  movieId  rating   timestamp
  37593     254     1721     3.5  1180446472
  37633     254     6539     4.0  1180446204),
 (263,
         userId  movieId  rating   timestamp
  38313     263     1721     4.0   940384199
  38412     263     6539     4.0  1090948146),
 (280,
         userId  movieId  rating   timestamp
  41286     280     1721     4.0  1348435240
  41350     280     6539     3.5  1348435219),
 (282,
         userId  movieId  rating   timestamp
  41524     282     1721     3.0  1378490504
  41641     282     6539     4.0  1378498775),
 (286,
         userId  movieId  rating   timestamp
  41900     286     1721     1.0  1119561957
  41955     286     6539     4.0  1119562462),
 (288,
         userId  movieId  rating   timestamp
  42410     288     1721     3.0   976121266
  42998     288     6539     4.0  1083091556),
 (301,
         userId  movieId  rating   timestamp
  45577     301     1721     1.5  1211377856
  45616     301     6539     4.0  1211377789),
 (304,
         userId  movieId  rating  timestamp
  45899     304     1721     5.0  885216165
  45907     304     1907     4.0  920201350),
 (305,
         userId  movieId  rating   timestamp
  46069     305     1721     3.5  1460365965
  46458     305    88163     4.0  1460303544),
 (318,
         userId  movieId  rating   timestamp
  49123     318     1907     3.5  1275845120
  49298     318     6539     3.5  1237233388),
 (328,
         userId  movieId  rating   timestamp
  50762     328     1907     3.0  1494210756
  50839     328     6539     3.5  1494212242),
 (352,
         userId  movieId  rating   timestamp
  53240     352     1721     4.0  1493673487
  53319     352     6539     4.0  1493675365),
 (357,
         userId  movieId  rating   timestamp
  54277     357     1721     4.0  1348611252
  54501     357    88163     4.5  1348611538),
 (358,
         userId  movieId  rating   timestamp
  54508     358     1721     5.0  1339546519
  54545     358    88163     4.0  1339546383),
 (361,
         userId  movieId  rating   timestamp
  54678     361     1721     2.0  1204045530
  54717     361     6539     3.5  1204045778),
 (365,
         userId  movieId  rating   timestamp
  54979     365     6539     3.5  1488332413
  55069     365    88163     2.5  1488594759),
 (370,
         userId  movieId  rating   timestamp
  56029     370     1721     3.5  1159162916
  56069     370     6539     4.0  1159163431),
 (382,
         userId  movieId  rating   timestamp
  58618     382     1721     5.0  1515160906
  58620     382     1907     4.5  1515161436),
 (387,
         userId  movieId  rating   timestamp
  59525     387     1907     2.5  1171934560
  59982     387     6539     3.5  1094876883),
 (401,
         userId  movieId  rating   timestamp
  61211     401     1907     3.5  1510455626
  61226     401     6539     3.5  1510455689),
 (416,
         userId  movieId  rating   timestamp
  65106     416     1721     0.5  1187496464
  65130     416     6539     2.0  1187496479),
 (420,
         userId  movieId  rating   timestamp
  65484     420     1721     4.0  1218207717
  65538     420     6539     4.0  1218207173),
 (432,
         userId  movieId  rating   timestamp
  66861     432     1721     4.0  1316391552
  66950     432     6539     0.5  1316391748),
 (448,
         userId  movieId  rating   timestamp
  69531     448     6539     3.5  1066291868
  69965     448    88163     3.5  1358608911),
 (462,
         userId  movieId  rating   timestamp
  71670     462     1721     2.5  1269929058
  71825     462     6539     4.0  1137445122),
 (477,
         userId  movieId  rating   timestamp
  75591     477     1721     3.5  1200939764
  75843     477     6539     3.0  1200945523),
 (480,
         userId  movieId  rating   timestamp
  76445     480     1721     4.0  1179178328
  76800     480     6539     3.0  1179163366),
 (484,
         userId  movieId  rating   timestamp
  78025     484     1721     3.0  1342295829
  78221     484    88163     4.0  1342297660),
 (489,
         userId  movieId  rating   timestamp
  78682     489     1721     3.5  1333101365
  78943     489     6539     2.0  1333101545),
 (495,
         userId  movieId  rating   timestamp
  79547     495     1721     5.0  1458635859
  79617     495     6539     2.5  1458635449),
 (517,
         userId  movieId  rating   timestamp
  81656     517     1721     3.5  1487953281
  81783     517     6539     2.5  1488397735),
 (523,
         userId  movieId  rating   timestamp
  82420     523     1721     5.0  1503126287
  82436     523     6539     4.5  1507987910),
 (537,
         userId  movieId  rating   timestamp
  84166     537     1721     3.0  1424141915
  84175     537     6539     5.0  1424317101),
 (542,
         userId  movieId  rating   timestamp
  84439     542     1721     3.0  1163387005
  84493     542     6539     4.0  1163386585),
 (561,
         userId  movieId  rating   timestamp
  86703     561     1721     3.0  1491091198
  86884     561     6539     4.5  1491095038),
 (562,
         userId  movieId  rating   timestamp
  87247     562     6539     3.0  1368893993
  87311     562    88163     5.0  1368896635),
 (563,
         userId  movieId  rating   timestamp
  87346     563     1907     3.5  1448749252
  87477     563    88163     3.5  1439933450),
 (570,
         userId  movieId  rating   timestamp
  88336     570     1721     3.0  1181477324
  88391     570     6539     3.5  1181479344)]

In [148]:
pearsonCorrelationDict={}

In [166]:
for name, group in filtro_rating_df_3:
    group = group.sort_values(by='movieId')
    choice_movies_1 = choice_movies_1.sort_values(by='movieId')
    movie=choice_movies_1[np.isin(choice_movies_1['movieId'], group['movieId'].tolist())]
    rating = movie['rating'].tolist()
    rating_1 = group['rating'].tolist()
    data_corr = {'tempGroupList': rating_1,
            'tempRatingList': rating}
    df_corr = pd.DataFrame(data_corr)
    dist_cosine = (1 / (1 +(pdist(df_corr, metric='cosine'))))
    pearsonCorrelationDict[name]=dist_cosine

In [167]:
coseno = pd.DataFrame.from_dict(pearsonCorrelationDict, orient='index')

In [168]:
coseno.columns = ["cero",'uno','dos','tres','cuatro','cinco','seis','siete','ocho','nueve']

In [169]:
coseno_1=coseno.loc[:,['cero']]

In [170]:
coseno_1.shape

(100, 1)

In [171]:
coseno_1.columns = ['usersimilares']
coseno_1['userId'] = coseno_1.index
coseno_1.index = range(len(coseno_1))
coseno_1.head()

   usersimilares  userId
0       0.971008     177
1       1.000000     414
2       0.957904      68
3       0.992611     232
4       0.944011     249

In [172]:
top_usuario=coseno_1.sort_values(by='usersimilares', ascending=False)[0:50]
top_usuario.head()

    usersimilares  userId
1             1.0     414
52            1.0     185
44            1.0     119
27            1.0     560
85            1.0     448

In [173]:
top_rating_usuario=top_usuario.merge(ratings_df, left_on='userId', right_on='userId', how='inner')
top_rating_usuario.head()

   usersimilares  userId  movieId  rating  timestamp
0            1.0     414        1     4.0  961438127
1            1.0     414        2     3.0  961594981
2            1.0     414        3     4.0  961439278
3            1.0     414        5     2.0  961437647
4            1.0     414        6     3.0  961515642

In [174]:
top_rating_usuario['pond_Rating'] = top_rating_usuario['usersimilares']*top_rating_usuario['rating']
top_rating_usuario.head()

   usersimilares  userId  movieId  rating  timestamp  pond_Rating
0            1.0     414        1     4.0  961438127          4.0
1            1.0     414        2     3.0  961594981          3.0
2            1.0     414        3     4.0  961439278          4.0
3            1.0     414        5     2.0  961437647          2.0
4            1.0     414        6     3.0  961515642          3.0

In [175]:
pond_top_rating_usuario = top_rating_usuario.groupby('movieId').sum()[['usersimilares','pond_Rating']]
pond_top_rating_usuario.columns = ['sum_usersimilares','sum_pond_Rating']
pond_top_rating_usuario.head()

         sum_usersimilares  sum_pond_Rating
movieId
1                35.931291       136.226142
2                21.953587        73.342663
3                 7.992752        25.979617
5                 6.994687        16.989074
6                12.973002        52.890091

In [176]:
recommendation_df = pd.DataFrame()

recommendation_df['weighted average recommendation score'] = pond_top_rating_usuario['sum_pond_Rating']/pond_top_rating_usuario['sum_usersimilares']
recommendation_df['movieId'] = pond_top_rating_usuario.index
recommendation_df.head()

         weighted average recommendation score  movieId
movieId
1                                     3.791295        1
2                                     3.340805        2
3                                     3.250397        3
5                                     2.428854        5
6                                     4.076935        6

In [177]:
recommendation_df = recommendation_df.sort_values(by='weighted average recommendation score', ascending=False)
recommendation_df.head(30)
print(movies_df.loc[movies_df['movieId'].isin(recommendation_df.head(30)['movieId'].tolist())])

      movieId                                             title  year
1707     2295                                    Impostors, The  1998
2947     3951                                  Two Family House  2000
5598    26928                    Summer's Tale, A (Conte d'été)  1996
5654    27523              My Sassy Girl (Yeopgijeogin geunyeo)  2001
6697    58301                                  Funny Games U.S.  2007
6939    65188  Dear Zachary: A Letter to a Son About His Father  2008
7271    74685                                      Crazies, The  2010
8030    98083                                       Jackass 3.5  2011
8775   128914                     Tom Segura: Completely Normal  2014
9365   162344                        Tom Segura: Mostly Stories  2016